changelog:
  categories:
    - title: New Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Packaging and Release
      labels:
        - release
        - packaging
        - build
        - ci
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Other Changes
      labels:
        - "*"